### ISSUE TITLE
part E in 2020 code jam

### ISSUE THREAD

**Issue by LakmalAsh** [andy1li/codejam#1]
Not working 
from itertools import permutations

Int  = lambda: int(input())
Ints = lambda: [*map(int, input().split())]

#------------------------------------------------------------------------------#

def solve():
    N, K = Ints()
    print(*permutations(range(1, N+1), N))
    return ''

#------------------------------------------------------------------------------#

for i in range(Int()):
    result = solve()
    print('Case #{}:'.format(i+1), result)

**Comment by andy1li** [comment]
It's not working because I haven't figured out how to solve the N ≤ 50 hidden test set yet. Since it would've sucked to type up a brute-force solution just to solve the N ≤ 5 simple test set, I decided to call it a day and wait for the official solution when the q round ends in about 9 hours.

**Comment by LakmalAsh** [comment]
Hey
i sorted it out i try for 20 min for that and i finished that thanks for
the help
